# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('screenshot1', models.ImageField(upload_to=b'')),
                ('screenshot2', models.ImageField(blank=True, upload_to=b'')),
                ('screenshot3', models.ImageField(blank=True, upload_to=b'')),
                ('description', models.TextField()),
                ('language1', models.CharField(max_length=100)),
                ('language2', models.CharField(blank=True, max_length=100)),
                ('language3', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
